spring:
  profiles:
    active: dev
  application:
    name: sicp 
  datasource:

    initial-size: 5
    min-idle: 5
    max-active: 100
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1 from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    #max-pool-prepared-statement-per-connection-size: 20    
    #filters: stat,wall,log4j    
    initialize: false
    #type: com.alibaba.druid.pool.DruidDataSource
    #connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000    
    auto-commit: true
    commit-on-return: true
    #maximum-pool-size: 15   
    #use-global-data-source-stat: true    
  jpa:    
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
  resources:
    cache-period: 1  
    
multipart:
  enabled: true
  file-size-threshold: 0
  max-file-size: 1000Mb
  max-request-size: 1010Mb
  
server: 
  context-path: /spring-boot-runner
  port: 8886
endpoints:
  health:
    sensitive: false
